# Generated by Django 5.0.3 on 2024-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
