# Generated by Django 5.0.3 on 2024-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=10)),
                ('rider_id', models.CharField(max_length=10)),
                ('driver_id', models.CharField(max_length=10)),
                ('pickUp_time', models.CharField(max_length=10)),
                ('pickup_from', models.CharField(max_length=50)),
                ('drop_to', models.CharField(max_length=50)),
                ('type_of_schedule', models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('custom', 'custom')], max_length=10, null=True)),
            ],
        ),
    ]
