# Generated by Django 5.0.3 on 2024-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
