# Generated by Django 5.0.3 on 2024-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schedule_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='weeks',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
