# Generated by Django 5.0.3 on 2024-03-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_schedule_driver_id_alter_schedule_rider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='rider_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='rider',
            name='id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='driver_id1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='rider_id1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rider'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pickUp_time',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
