# Generated by Django 5.0.3 on 2024-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_schedule_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='driver_id1',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='rider_id1',
            new_name='rider_id',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pickUp_time',
            field=models.CharField(max_length=10),
        ),
    ]
