# Generated by Django 5.0.3 on 2024-03-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_driver_id1_schedule_driver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='driver_id',
            new_name='driver_id1',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='rider_id',
            new_name='rider_id1',
        ),
    ]
