# Generated by Django 5.0.3 on 2024-03-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_driver_id_schedule_driver_id1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
