# Generated by Django 5.0.3 on 2024-03-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='person',
            new_name='persons',
        ),
    ]
