# Generated by Django 5.0.3 on 2024-04-24 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_persons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='driver_id1',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='rider_id1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='driver_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='rider_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('isRider', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
    ]
