# Generated by Django 5.0.3 on 2024-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_schedule_rider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='endDate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='startDate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
